<a href="https://colab.research.google.com/github/R1fky/machineLearning/blob/main/preprocessing_dataSklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# sample data
import numpy as np
from sklearn import preprocessing

sampleData = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

sampleData

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [4]:
sampleData.shape

(4, 3)

In [8]:
# preprocessing Binarizer
preprocessor = preprocessing.Binarizer(threshold=5) # akan diubah menjadi biner jika nilai pada array lebih kecil dari threshold
binerIzed = preprocessor.transform(sampleData)
binerIzed

array([[0, 0, 0],
       [0, 0, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [9]:
sampleData

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
# scalling
preprocessor = preprocessing.MinMaxScaler(feature_range=(0, 1))
preprocessor.fit(sampleData)
scaled_data = preprocessor.transform(sampleData)
scaled_data


array([[0.        , 0.        , 0.        ],
       [0.33333333, 0.33333333, 0.33333333],
       [0.66666667, 0.66666667, 0.66666667],
       [1.        , 1.        , 1.        ]])

In [20]:
scaled_data = preprocessor.fit_transform(sampleData)
scaled_data

array([[0.        , 0.        , 0.        ],
       [0.33333333, 0.33333333, 0.33333333],
       [0.66666667, 0.66666667, 0.66666667],
       [1.        , 1.        , 1.        ]])

In [23]:
# l2 normalisation
sampleData

l2_normalised_data = preprocessing.normalize(sampleData, norm='l2')
l2_normalised_data

array([[0.26726124, 0.53452248, 0.80178373],
       [0.45584231, 0.56980288, 0.68376346],
       [0.50257071, 0.57436653, 0.64616234],
       [0.52342392, 0.57576631, 0.62810871]])